#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: FATES development notebooks
author: Gregory Lemieux  
logo: ngeet.png  

# Build settings
only_build_toc_files: true
exclude_patterns: [california/data,fates_next_api-rebase/Test-Cases,
                  leaf-flutter/acre-output, leaf-flutter/scratch]

# Execution settings
execute:
  execute_notebooks: off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

# Sphinx configuration
sphinx:
  extra_extensions: [sphinx_rtd_theme]
  config:
    html_theme: sphinx_rtd_theme
    html_theme_options: {'logo_only': True,'display_version': False}

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: fates_dev_notebooks.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/glemieux/fates-jupyter  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true